apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::322299679673:role/bank-app-to-ecr
      username: kubernetes-admin
      groups:
        - system:masters